dist: trusty
language: groovy
addons:
  chrome: stable
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- openjdk8
script: "./travis-build.sh"
env:
  global:
  - secure: damKp0mLGZSktisYUjGMZ8sY6YVOBA4k8dtbgjZnn7yVjBa5XtsgCFVB9SswyqxZgJn05sP9ZmgtHgUG7jugZAtxIT8jRjjxkV0MkdpeFiy3v2vdSCYHCZ6vpbwNZpfFJ9yjYtZ2w39N6BpCwi5+TZccFowYNMG1ug0wdd2MzLQ=
  - secure: STIEg7/twxodFmN/u4sEUE68cytdmT7s8arsAApEl88BOz6beBS/hb8zcee6Goqn6glLzpuPAkpziKK86YT8mALSlkVSMRffNjPcTBWTR0+2Cg6b8sM0Hr6fZZ6h3984ddxHVLz/ncqm7XN7ucvfzAczEe6jn7J7R1geki1kM8Y=
  - secure: YoKRQEzITmJO6BHrFqLDIWuzLxnAIwOGSenEHgq3aLHrJHXZppgi2hIhCgpOn4t2tsqEkur4v+/JQWa+JvmM3BsBCanEC1fEF7SvgJ8OHTAMVfmKaE0RCFQ9/K8sos0MHuhSSZoz1qQpgCtI/h5xLoZvGuxC0h81U8SYBum+XQE=
  - secure: EaeQoN2pMqFpC6o0POHNxUy5adFIMNr4ON6cXgbmmCqyCJK5hDiFF6Nf9eZdKUJdU2wlO22x9W8D56TabvlRzisHK88JsHsolIKBd/RYJOd+fXoq/swXKfW758erGWIm97ELPSE9ijmi7JDdEy3vaxzVA+L3gigYtfQqGXihD+c=
  - secure: B39UbdOM6ViWRTNXv0KhTfr42Gi1ZZDPLTK8TAFykigdxqnyNTGgsHQqWcB4algAl6wCMMR458wynGu6wHa2EKSuC3BQCZdKyhQnJNLqW/cx+IikkbTi2EmsQs0exheiaWJyAnUyLGZA8hJp+rPpc5BHZIAr4+mYTM6QVmuUqtU=
