dist: trusty
language: groovy
addons:
  chrome: stable
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- openjdk8
script: "./travis-build.sh"
env:
  global:
  - secure: JI9eT4Jvlm9UtN05e4Ul7vcjemDaQcEedk6PkDWgaWEjAqGbdWG8m+Os1MjrwGy2XqJF1GcLUa/ND7Apqn1OMUoBRL9T28f2PdEAO9Fc54arQ0EWbwXO7u+d3tbtsMMXDvMf3UxlRfti3TPmSrcwz7CWK0qE0IJX7i3q8CCHHTk=
  - secure: MylsdRDE8OI08MA6B3mC2xE+5elrU5vfmFbecBrwmeL0kAK8B4w+zNcL/Axt0PN49fw1c8tQTDJA+TFIBMEW8YiDbozb9CLYcsF5bhxwPfO3jYO18mCao+EXaz0LEigiptTIhCpEtLobEvi9KwQhb4W+ESuILekz3IWYpfK4kVw=
  - secure: DO1jUSjYPv9qzPC0R+n9EBi5PMNVhuuq/Lz13/RvWahcaLb3khGREbxVxY8V9A91X2ktU3fOSfbkwutvOVK4gMxxa0L9HhhR31cnAr9eM0LEmM7J/U39/Uo04wHwTflV1KYk9DMHa+0p5CnVQNHE5345SjFJt2jeOnxQE+flJ8o=
  - secure: UAZ4sSFAXo0vWlEfIC5E89O9qf8Ixwg+qySEaUb79Xf5bEljUtMqy2KrzhFAN+RDlTIYKMb23SVpZmKrBsh8glMbliFE4H/PlkD0qwbEwnAp1LrLmnfaTEFdSUYFZCrOcdBluiHtrYpyj+TrVkgm8++g3sblpIK5Wqspsism1VI=
  - secure: Xua7mlpZjG+KD/EGeKE0IsmweXso3A0HXCSXmBcJks7mS3ktt+JfxQtY+hEBS9K9bNydXA2ZdtYWvGBGLcvk4jszZenWcYIF7OxBMHi+1HSQeyzIcOMTWj3cSpm51+R1QqLVDFiWnF1sZwNunJ3pAE/eJLSjpqxoms+xA9RJL+g=
